version: '3.3'

services:
  #service 2: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: ghcr.io/sheremet-vlad/bk-graber-server:master #name of the image after dockerfile executes
    ports:
      - "8084:8080"                       #docker containter port with your os port
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://172.17.0.1:3306/graber?autoReconnect=true&useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "1234"
          }'
    volumes:
      - bind-log-file:/home/bkGraberServer/logs

volumes:
  bind-log-file:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bkGraberServer/logs
